# Generated by Django 5.2 on 2025-08-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_auth_options_alter_auth_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth',
            options={},
        ),
        migrations.AlterModelManagers(
            name='auth',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='auth',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='auth',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
