# Generated by Django 5.2 on 2025-08-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='images/blank_image.png', null=True, upload_to='images/'),
        ),
    ]
