# Generated by Django 5.2 on 2025-09-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='blank_image.png', null=True, upload_to=''),
        ),
    ]
