# Generated by Django 5.2 on 2025-09-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('food', 'Food'), ('home', 'Home'), ('gaming', 'Gaming')], default='fashion', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='blank_image.png', null=True, upload_to=''),
        ),
    ]
